index.js

1. Firefox Developer folder name in OS X is FirefoxDeveloperEdition.app, not
FirefoxDeveloper.app
2. Existing Aurora users were auto-updated to Firefox Developer Edition without
changing the folder where the browser was installed; this commit makes the
configuration fallback to the previous directory.

fix: Fix Firefox Developer Edition config

---

index.js

One line change to support FreeBSD without requiring users on that platform to set the FIREFOX_BIN env variable.

FreeBSD support OOTB.

---

index.js

Cause of supporting client certificates we needed to start firefox with a custom profile folder.
Therefor I used the `customLauncher` attributes of Karma to set the path to the firefox launcher, but it ignored it. So I have done this change.
New with the following config the firefox starts with the given profile 
```
customLaunchers: {
FirefoxProfile: {
base: 'Firefox',
profile: '<path to profile>'
}
},
```

add support of custom profile by using customLaunchers of karma config

---

.gitignore
README.md
index.js

See https://mike.kaply.com/2012/02/21/understanding-add-on-scopes/ for more details on `extensions.autoDisableScopes` and `extensions.enableScopes` preferences. Setting them ensures that extensions located in the user's profile will be loaded.
Closes #33

feat: add support for loading extensions

---

index.js

Firefox slows down execution of timing functions (like setTimeout)
when running in the background. This disables that behavior
so that tests will run quickly even with the browser window
minimized.
Fixes #19

speed up background execution

---

index.js

Firefox has issue with VirtualBox shared folders https://bugzilla.mozilla.org/show_bug.cgi?id=801274 which is used with Docker setup. This change allow to specify profile path outside of shared folder ( e.g. /tmp/firefox ) and thus make firefox start properly.
Fixes #43

feat: allow user to specify profile folder location

---

index.js

When firefox is installed with brew cask, then it's installed into user's home dir (~/Applications), but launcher expects firefox's location in /Applications dir, so it hangs. This PR makes it work with both destinations (~/Applications, /Applications).
Fixes #42 too.

Firefox installed in user's home directory [macos]

---

index.js

As far as I can tell, this fixes #61 (though it could benefit from more testing).
I've tested this with Gitlab-Runner on a Windows 10 VM with Firefox 51.0.1

Disable multi-process Firefox

---

index.js

This change prevents the OS X karma runtime from dying prematurely due to the plugin not starting correctly because the `HOME` environment being unset for whatever reason. Similar plugins such as the [karma-chrome-launcher](https://github.com/karma-runner/karma-chrome-launcher/blob/master/index.js#L135) have similar safeguards in place already.
Also, this function may potentially return `undefined` if the for loop is exhausted without producing a valid result, not sure if this is intended.
For more information, this issue can be reproduced very clearly with a repository I [created explicitly to reproduce this issue](https://github.com/metatoaster/karma-firefox-launcher-bug-demo/tree/failure), and the respective [failure](https://travis-ci.org/metatoaster/karma-firefox-launcher-bug-demo/job …

Only use HOME environmental variable if exists

---

.travis.yml

As referenced in [PR 77](https://github.com/karma-runner/karma-firefox-launcher/pull/77) `npm5` no longer supports these old versions. Dropping them should resolving the build errors for that PR.

Remove depracted Node versions from Travis.yml

---

index.js

[Issue #67] On Windows 10, Karma will not load the launcher plugin, throwing the error `Cannot read property 'substr' of undefined`. People reported this behaviour happening on Windows 7 as well.
This was caused by an undefined prefix at `getAllPrefixes()`, specifically `process.env['PROGRAMFILES(X86)']`). I've simply added a check for undefined prefix strings.
Sorry, but I could test this ONLY on Windows 10.

Fix for issue 67

---

.travis.yml
karma.conf.js

Starting xvfb on travis has changed:
https://benlimmer.com/2019/01/14/travis-ci-xvfb/
Also trying to use nodejs 4 just fails because the yarn script doesn't
appear to support it. We probably don't need to test on node 4 anymore
anyway.
Also, I'm not sure why the karma config was specifying singleRun: false.
It seems like we probably do want a single run here.

chore: Fix travis

---

index.js

More recent installs of Firefox Nightly on Windows use "Firefox Nightly" instead of "Nightly" for the application folder. Apparently OSX uses "Firefox Nightly" instead of "FirefoxNightly" too.

Look for other paths for Firefox Nightly

---

index.js

As of about Firefox 64, on Windows Firefox uses a separate launcher process which then spawns the browser process. The launcher process will terminate quickly causing karma to think something failed.
As with Mozilla's own automation tests we should use `-wait-for-browser` to make the launcher process wait for the browser process to complete and return its exit code.
Unfortunately, killing the launcher process won't kill the browser process so this isn't a complete solution. However, killing the browser process is likely more complicated while simply getting the browser to launch at all is probably enough for local testing.
This builds on top of #94 so I expect you'll want to merge that first.

Add wait for browser

---

.travis.yml

End-of-life was 2019-04-30 and supporting it stops us from using
dependencies that require Node 8 (e.g. is-wsl).

chore: Drop support for Node 6

---

index.js

If the wsl path contains non-existent paths then trying to convert using wslpath causes an error

fix: Check that wsl path exists before using wslpath to convert it

---

index.js
package.json
yarn.lock

is-wsl in previous versions returns true when running in docker under wsl.  This then causes an error because the wslpath command is not found.

Update is-wsl to v2.2.0 to detect docker under WSL

---

.travis.yml

BREAKING CHANGE: Changed minimum required version of node.js from 8 to 10.
Node 8 EOL was 2019-12-31.
Fixes #118.

feat: Make Node 10 minimum required version

---

README.md
index.js

Provide a way to configure location of executable in customLauncher

---

index.js

Hi everyone, this PR updates the name that the plugin uses to locate the Developer Edition on macOS. For quite some time now the name is "Firefox Developer Edition" with spaces. The old name is still available as a fallback which means this should not be a breaking change.
Please let me know if I should change anything to make this PR acceptable.

fix: update name of Developer Edition on macOS

---

index.js

**Record PIDs for firefox.exe on WSL and kill all processes not recorded on start-up.**
After testing both regular Firefox and Firefox Developer Edition, I came to the conclusion that the executable is always `firefox.exe` - I really hope that is correct.
At first I wrote this patch in ES5 but since we already use destructuring assignment at the top (`var { execSync } = require('child_process')`), I re-wrote it to ES6/ES2015.
According to SO the highest PID on Windows is [0xFFFFFFFC](https://stackoverflow.com/questions/17868218/what-is-the-maximum-process-id-on-windows) which I believe is 10 digits. The lowest PID is 0 but only PIDs above 100 seems to be user-land processes. The first ones seems to be reserved for Windows OS. The way I extract PIDs is by looking for _whole_ integers, so I …

fix: launcher does not kill firefox.exe on WSL
